#!/usr/bin/env bash
# Auto-generated by scripts/blueprint_to_issues.py.
# Run with --dry-run to preview, no args to actually create the issues.
set -euo pipefail

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

gh_call() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf "DRY: gh"; for a in "$@"; do printf " %q" "$a"; done; printf "\n"
  else
    gh "$@"
  fi
}

# ---------- ensure labels exist (idempotent: --force updates if present) ----------
gh_call label create 'area:bochner' --color FBCA04 --force
gh_call label create 'area:dense-extension' --color FBCA04 --force
gh_call label create 'area:fubini' --color FBCA04 --force
gh_call label create 'area:hilbert-sum' --color FBCA04 --force
gh_call label create 'area:tensor' --color FBCA04 --force
gh_call label create 'chapter:approx-id' --color BFD4F2 --force
gh_call label create 'chapter:conv' --color BFD4F2 --force
gh_call label create 'chapter:isotypic' --color BFD4F2 --force
gh_call label create 'chapter:matrix' --color BFD4F2 --force
gh_call label create 'chapter:orthog' --color BFD4F2 --force
gh_call label create 'chapter:rep' --color BFD4F2 --force
gh_call label create 'chapter:schur' --color BFD4F2 --force
gh_call label create 'chapter:separating' --color BFD4F2 --force
gh_call label create 'chapter:spectral' --color BFD4F2 --force
gh_call label create 'external:mathlib-gap' --color B60205 --force
gh_call label create 'priority:p1' --color D93F0B --force
gh_call label create 'priority:p2' --color FBCA04 --force
gh_call label create 'priority:p3' --color C5DEF5 --force
gh_call label create 'type:atomic' --color 0E8A16 --force
gh_call label create 'type:cluster' --color 1D76DB --force

# ---------- atomic issues (auto-generated) ----------
gh_call issue create --title '[def:leftTransL2] Left translation as a map on L^2' --body-file scripts/issue-seeds/atomic/def_leftTransL2.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[thm:leftTrans-unitary] \lambda_g is unitary' --body-file scripts/issue-seeds/atomic/thm_leftTrans-unitary.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[thm:leftTrans-mulHom] \lambda is a group homomorphism on L^2' --body-file scripts/issue-seeds/atomic/thm_leftTrans-mulHom.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[thm:leftTrans-strongCts] The orbit map of left translation is continuous' --body-file scripts/issue-seeds/atomic/thm_leftTrans-strongCts.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[def:leftReg] The left regular representation \rho^L' --body-file scripts/issue-seeds/atomic/def_leftReg.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[def:rightTransL2] Right translation as a map on L^2' --body-file scripts/issue-seeds/atomic/def_rightTransL2.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[def:rightReg] The right regular representation \rho^R' --body-file scripts/issue-seeds/atomic/def_rightReg.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[thm:LR-commute] \rho^L and \rho^R commute' --body-file scripts/issue-seeds/atomic/thm_LR-commute.md --label type:atomic --label chapter:rep --label area:dense-extension
gh_call issue create --title '[thm:conv-CS] Cauchy--Schwarz bound for pointwise convolution' --body-file scripts/issue-seeds/atomic/thm_conv-CS.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:conv-cts] f*\phi is continuous when f, \phi \in L^2' --body-file scripts/issue-seeds/atomic/thm_conv-cts.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:conv-L2bound] L^2 norm bound for convolution' --body-file scripts/issue-seeds/atomic/thm_conv-L2bound.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[def:Tphi] Bounded operator T_\phi' --body-file scripts/issue-seeds/atomic/def_Tphi.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:Tphi-comm-rightReg] T_\phi commutes with right translation' --body-file scripts/issue-seeds/atomic/thm_Tphi-comm-rightReg.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:Tphi-adj] Adjoint of T_\phi' --body-file scripts/issue-seeds/atomic/thm_Tphi-adj.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[cor:Tphi-selfadj] T_\phi self-adjoint when \phi symmetric' --body-file scripts/issue-seeds/atomic/cor_Tphi-selfadj.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:Tphi-compact] T_\phi is a compact operator' --body-file scripts/issue-seeds/atomic/thm_Tphi-compact.md --label type:atomic --label chapter:conv --label area:fubini
gh_call issue create --title '[thm:bump-exists] Existence of continuous bumps' --body-file scripts/issue-seeds/atomic/thm_bump-exists.md --label type:atomic --label chapter:approx-id
gh_call issue create --title '[thm:bump-conv-tendsto] Convergence of bump-convolution to identity, L^2' --body-file scripts/issue-seeds/atomic/thm_bump-conv-tendsto.md --label type:atomic --label chapter:approx-id
gh_call issue create --title '[def:RealImag] Self-adjoint and skew parts of an operator' --body-file scripts/issue-seeds/atomic/def_RealImag.md --label type:atomic --label chapter:schur
gh_call issue create --title '[thm:schur-distinct] Schur for non-equivalent compact intertwiner targets' --body-file scripts/issue-seeds/atomic/thm_schur-distinct.md --label type:atomic --label chapter:schur
gh_call issue create --title '[thm:mc-sum] Sum of matrix coefficients is a matrix coefficient' --body-file scripts/issue-seeds/atomic/thm_mc-sum.md --label type:atomic --label chapter:matrix --label area:tensor
gh_call issue create --title '[def:tensor-rep] Tensor product of unitary reps' --body-file scripts/issue-seeds/atomic/def_tensor-rep.md --label type:atomic --label chapter:matrix --label area:tensor
gh_call issue create --title '[thm:mc-mul] Product of matrix coefficients' --body-file scripts/issue-seeds/atomic/thm_mc-mul.md --label type:atomic --label chapter:matrix --label area:tensor
gh_call issue create --title '[def:contragredient] Contragredient (dual) representation' --body-file scripts/issue-seeds/atomic/def_contragredient.md --label type:atomic --label chapter:matrix --label area:tensor
gh_call issue create --title '[thm:mc-conj] Conjugate of a matrix coefficient' --body-file scripts/issue-seeds/atomic/thm_mc-conj.md --label type:atomic --label chapter:matrix --label area:tensor
gh_call issue create --title '[thm:rightReg-faithful] Right regular action is faithful' --body-file scripts/issue-seeds/atomic/thm_rightReg-faithful.md --label type:atomic --label chapter:separating
gh_call issue create --title '[thm:existsSepConv] Existence of separating self-adjoint convolution operator' --body-file scripts/issue-seeds/atomic/thm_existsSepConv.md --label type:atomic --label chapter:separating
gh_call issue create --title '[thm:eigenspace-separates] T_\phi has a non-zero finite-dim eigenspace separating
  g_0' --body-file scripts/issue-seeds/atomic/thm_eigenspace-separates.md --label type:atomic --label chapter:separating
gh_call issue create --title '[thm:fd-irr-nontrivial] Finite-dim invariant non-trivial action splits to non-trivial irreducible action' --body-file scripts/issue-seeds/atomic/thm_fd-irr-nontrivial.md --label type:atomic --label chapter:separating
gh_call issue create --title '[thm:mc-orthog-distinct] Inner product of matrix coefficients across distinct irreducibles' --body-file scripts/issue-seeds/atomic/thm_mc-orthog-distinct.md --label type:atomic --label chapter:orthog --label area:bochner
gh_call issue create --title '[thm:mc-orthog-same] Inner product of matrix coefficients of same irreducible' --body-file scripts/issue-seeds/atomic/thm_mc-orthog-same.md --label type:atomic --label chapter:orthog --label area:bochner
gh_call issue create --title '[thm:isotypic-invariant] L^2(G)_\xi is \rho^R-invariant' --body-file scripts/issue-seeds/atomic/thm_isotypic-invariant.md --label type:atomic --label chapter:isotypic --label area:bochner
gh_call issue create --title '[thm:isotypic-orthog] Distinct isotypic components are orthogonal' --body-file scripts/issue-seeds/atomic/thm_isotypic-orthog.md --label type:atomic --label chapter:isotypic --label area:bochner
gh_call issue create --title '[thm:mc-in-isotypic] Matrix coefficients of \rho_\xi live in L^2(G)_\xi' --body-file scripts/issue-seeds/atomic/thm_mc-in-isotypic.md --label type:atomic --label chapter:isotypic --label area:bochner
gh_call issue create --title '[thm:isotypic-spans] Closed sum of isotypic components is dense' --body-file scripts/issue-seeds/atomic/thm_isotypic-spans.md --label type:atomic --label chapter:isotypic --label area:bochner
gh_call issue create --title '[thm:PW-HilbertSum] L^2(G) is the Hilbert sum of isotypic components' --body-file scripts/issue-seeds/atomic/thm_PW-HilbertSum.md --label type:atomic --label chapter:isotypic --label area:bochner
gh_call issue create --title '[thm:plancherel-isotypic] Plancherel: per-isotypic norm sum' --body-file scripts/issue-seeds/atomic/thm_plancherel-isotypic.md --label type:atomic --label chapter:isotypic --label area:bochner

# ---------- cluster issues (hand-written; review before running) ----------
gh_call issue create --title '[Cluster] Ch.10 Schur orthogonality: Bochner integration scaffolding' --body-file scripts/issue-seeds/cluster-ch10-bochner-orthogonality.md --label type:cluster --label chapter:orthog --label area:bochner --label priority:p1
gh_call issue create --title '[Cluster] Ch.11 Isotypic decomposition + Plancherel' --body-file scripts/issue-seeds/cluster-ch11-isotypic-plancherel.md --label type:cluster --label chapter:isotypic --label area:bochner --label area:hilbert-sum --label priority:p1
gh_call issue create --title '[Cluster] Ch.2 Regular representations: dense extension of translation from C(G) to L²(G)' --body-file scripts/issue-seeds/cluster-ch2-regular-representations.md --label type:cluster --label chapter:rep --label area:dense-extension --label priority:p1
gh_call issue create --title '[Cluster] Ch.3 Convolution: Fubini and change-of-variables on L²(G)' --body-file scripts/issue-seeds/cluster-ch3-convolution.md --label type:cluster --label chapter:conv --label area:fubini --label priority:p1
gh_call issue create --title '[Cluster] Ch.7 Matrix coefficients: tensor and contragredient representations' --body-file scripts/issue-seeds/cluster-ch7-matrix-coefficients.md --label type:cluster --label chapter:matrix --label area:tensor --label priority:p2
gh_call issue create --title '[Cluster] Ch.8 Separating irreducibles: downstream wiring of Chs. 2/3/4' --body-file scripts/issue-seeds/cluster-ch8-separating-irreducibles.md --label type:cluster --label chapter:separating --label priority:p3

# ---------- external assumption issues (hand-written) ----------
gh_call issue create --title '[External] Adjoint of a compact operator is compact (Schauder, Mathlib gap)' --body-file scripts/issue-seeds/external-compact-adjoint.md --label external:mathlib-gap --label chapter:schur --label chapter:conv
gh_call issue create --title '[External] Compact self-adjoint spectral theorem (Mathlib gap)' --body-file scripts/issue-seeds/external-spectral-decomposition.md --label external:mathlib-gap --label chapter:spectral

# ---------- link cluster checkboxes to atomic issue numbers ----------
# Idempotent; safe to re-run if seed.sh is partially redone.
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRY: python3 scripts/link_cluster_issues.py"
else
  python3 scripts/link_cluster_issues.py
fi
