/-
Copyright (c) 2026.  Released under Apache 2.0 license.
-/
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import PeterWeylComp.MatrixCoeff
import PeterWeylComp.Separating

/-!
# Peter–Weyl, Chapter 9: Density of Matrix Coefficients

This file formalises Chapter 9 of the compact Peter–Weyl blueprint
(`blueprint/src/content_comp.tex`).  Combining Chapter 8's
`exists_separating_irreducible` (existence of a finite-dim irreducible
on which `g₀ ≠ 1_G` acts non-trivially) with Chapter 7's
`matrixCoeffSubalgebra` (the star-subalgebra of `C(G, ℂ)` generated by
matrix coefficients), we conclude that `matrixCoeffSubalgebra` is
uniformly dense in `C(G, ℂ)` (Stone–Weierstrass) and `L²`-dense in
`L²(G)`.

## Mathlib survey

The Stone–Weierstrass step (item 4) is a direct citation:

* `ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints`
  (`Mathlib/Topology/ContinuousMap/StoneWeierstrass.lean:399`):
  for a star-subalgebra `A ⊆ C(X, 𝕜)` (with `[CompactSpace X]` and
  `RCLike 𝕜`), `A.SeparatesPoints` implies `A.topologicalClosure = ⊤`.

For item 5, `DenseRange.dense_image`
(`Mathlib/Topology/Continuous.lean:284`) bridges uniform density in
`C(G, ℂ)` to `L²` density via the dense embedding
`PeterWeyl.continuousMapToL2`.

## Universe note

`matrixCoeffSet G` quantifies over `V : Type u` where `u` is `G`'s
universe (see Chapter 7).  This is consistent with Chapter 8's
`exists_separating_irreducible`, which produces a submodule `W' ≤ L²(G)`
at the same universe.
-/

open scoped MeasureTheory ENNReal NNReal InnerProductSpace

universe u

namespace UnitaryRep

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]

/-! ## Auxiliary: matrix-coefficient translation identity -/

omit [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
  [MeasurableSpace G] [BorelSpace G] in
/-- Translating the first vector of a matrix coefficient by a group
element shifts the argument: for `σ : UnitaryRep G V` and `u, v : V`,
`σ.matrixCoeff (σ g₀ u) v g = σ.matrixCoeff u v (g * g₀)`. -/
theorem matrixCoeff_left_translate
    {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℂ V] [CompleteSpace V]
    (σ : UnitaryRep G V) (g₀ g : G) (u v : V) :
    σ.matrixCoeff (σ g₀ u) v g = σ.matrixCoeff u v (g * g₀) := by
  show ⟪σ g (σ g₀ u), v⟫_ℂ = ⟪σ (g * g₀) u, v⟫_ℂ
  congr 1
  show (σ.toMonoidHom g) ((σ.toMonoidHom g₀) u) = (σ.toMonoidHom (g * g₀)) u
  rw [σ.toMonoidHom.map_mul]; rfl

/-! ## Item 1: restriction matrix coefficients -/

omit [T2Space G] in
/-- (`thm:restrict-to-mc`) The matrix coefficient of the restriction
of `ρ^R` to a finite-dim `ρ^R`-invariant subspace `W ⊆ L²(G)` belongs
to `matrixCoeffSet G`. -/
theorem restrict_matrixCoeff_eq_matrixCoeff
    (W : (PeterWeyl.rightReg G).Subrep) [FiniteDimensional ℂ W.toSubmodule]
    (u v : W.toSubmodule) :
    letI : CompleteSpace W.toSubmodule := W.completeSpace_toSubmodule
    (W.restrict).matrixCoeff_continuousMap u v
      ∈ matrixCoeffSet G := by
  letI : CompleteSpace W.toSubmodule := W.completeSpace_toSubmodule
  exact ⟨W.toSubmodule, _, _, _, ‹_›,
    W.restrict, u, v, rfl⟩

/-! ## Item 2: `matrixCoeffSet` separates points -/

/-- (`thm:MCSet-separates`) `matrixCoeffSet G` separates points of
`G`: for every pair `g₁ ≠ g₂`, there is a matrix coefficient
distinguishing them. -/
theorem matrixCoeffSet_separatesPoints :
    Set.SeparatesPoints
      ((fun f : C(G, ℂ) => (f : G → ℂ)) '' matrixCoeffSet G) := by
  intro g₁ g₂ h_ne
  -- Apply Chapter 8 with `g₀ := g₁ * g₂⁻¹ ≠ 1`.
  have hg_ne : g₁ * g₂⁻¹ ≠ 1 := by
    intro h
    apply h_ne
    have := mul_inv_eq_one.mp h
    exact this
  obtain ⟨W', hW'_ne, hW'_closed, hW'_fd, hW'_inv, _hW'_irr, ⟨u₀, hu₀_W, hu₀_act⟩⟩ :=
    PeterWeyl.exists_separating_irreducible (g₁ * g₂⁻¹) hg_ne
  -- Bundle W' as a Subrep of rightReg.
  let W : (PeterWeyl.rightReg G).Subrep :=
    { toSubmodule := W'
      isClosed := hW'_closed
      invariant := hW'_inv }
  haveI : FiniteDimensional ℂ W.toSubmodule := hW'_fd
  letI : CompleteSpace W.toSubmodule := W.completeSpace_toSubmodule
  -- Rename: σ := ρ^R|_W'
  set σ : UnitaryRep G W.toSubmodule := W.restrict
  -- u₀ as a vector in W.toSubmodule
  let uW : W.toSubmodule := ⟨u₀, hu₀_W⟩
  -- Define v := σ (g₁ g₂⁻¹) uW - uW ∈ W.toSubmodule (W is invariant under σ).
  set vW : W.toSubmodule := σ (g₁ * g₂⁻¹) uW - uW with hvW_def
  -- vW ≠ 0 because σ acts non-trivially on uW.
  have hvW_ne : vW ≠ 0 := by
    intro h
    apply hu₀_act
    -- vW = 0 ⟹ σ (g₁*g₂⁻¹) uW = uW (in W.toSubmodule).
    have h_eq : σ (g₁ * g₂⁻¹) uW = uW := sub_eq_zero.mp (hvW_def ▸ h)
    -- Coerce both sides to L2 G to get the desired equality.
    exact congrArg (fun (x : W.toSubmodule) => (x : PeterWeyl.L2 G)) h_eq
  -- Define u := σ (g₂⁻¹) uW.  Then π_{u, vW}(g) = π_{uW, vW}(g · g₂⁻¹).
  let u : W.toSubmodule := σ g₂⁻¹ uW
  -- f := σ.matrixCoeff_continuousMap u vW
  refine ⟨σ.matrixCoeff_continuousMap u vW, ⟨_, ?_, rfl⟩, ?_⟩
  · -- f ∈ matrixCoeffSet G via item 1.
    exact restrict_matrixCoeff_eq_matrixCoeff (G := G) W u vW
  · -- π_{u, vW}(g₁) ≠ π_{u, vW}(g₂).
    show σ.matrixCoeff u vW g₁ ≠ σ.matrixCoeff u vW g₂
    rw [show u = σ g₂⁻¹ uW from rfl,
        matrixCoeff_left_translate σ g₂⁻¹ g₁ uW vW,
        matrixCoeff_left_translate σ g₂⁻¹ g₂ uW vW]
    -- σ.matrixCoeff uW vW (g₁ * g₂⁻¹) ≠ σ.matrixCoeff uW vW (g₂ * g₂⁻¹).
    rw [mul_inv_cancel]
    -- σ.matrixCoeff uW vW (g₁ * g₂⁻¹) ≠ σ.matrixCoeff uW vW 1.
    show ⟪σ (g₁ * g₂⁻¹) uW, vW⟫_ℂ ≠ ⟪σ 1 uW, vW⟫_ℂ
    -- σ 1 uW = uW, so RHS = ⟪uW, vW⟫.  Difference = ⟪σ(g₁g₂⁻¹) uW - uW, vW⟫ = ⟪vW, vW⟫ ≠ 0.
    intro h
    apply hvW_ne
    have h_diff : ⟪σ (g₁ * g₂⁻¹) uW - uW, vW⟫_ℂ = 0 := by
      rw [inner_sub_left, sub_eq_zero]
      have h_one : σ.toMonoidHom 1 uW = uW := by
        rw [σ.toMonoidHom.map_one]; rfl
      rw [show σ 1 uW = uW from h_one] at h
      exact h
    rw [← hvW_def] at h_diff
    -- ⟪vW, vW⟫ = 0 ⟹ vW = 0.
    exact inner_self_eq_zero.mp h_diff

/-! ## Item 3: `matrixCoeffSubalgebra` separates points -/

/-- (`cor:MCAlg-separates`) The matrix-coefficient star-subalgebra
separates points of `G`. -/
theorem matrixCoeffSubalgebra_separatesPoints :
    (matrixCoeffSubalgebra G).SeparatesPoints := by
  -- The set `matrixCoeffSet G` is contained in `matrixCoeffSubalgebra G`,
  -- and separates points by item 2; superset preserves separation.
  intro g₁ g₂ h_ne
  obtain ⟨f, ⟨φ, hφ_set, hφ_eq⟩, h_neq⟩ :=
    matrixCoeffSet_separatesPoints (G := G) h_ne
  -- φ : C(G, ℂ), hφ_set : φ ∈ matrixCoeffSet G,
  -- hφ_eq : ⇑φ = f, h_neq : f g₁ ≠ f g₂.
  refine ⟨f, ⟨φ, ?_, hφ_eq⟩, h_neq⟩
  -- φ ∈ matrixCoeffSubalgebra G via subset_adjoin.
  exact StarAlgebra.subset_adjoin ℂ _ hφ_set

/-! ## Item 4: Stone–Weierstrass density in `C(G, ℂ)` -/

/-- (`thm:MCAlg-CG-dense`) The matrix-coefficient star-subalgebra is
uniformly dense in `C(G, ℂ)`: its topological closure is `⊤`.

Direct application of
`ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints`. -/
theorem matrixCoeffSubalgebra_topologicalClosure_eq_top :
    (matrixCoeffSubalgebra G).topologicalClosure = ⊤ :=
  ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints
    (matrixCoeffSubalgebra G) matrixCoeffSubalgebra_separatesPoints

/-! ## Item 5: `L²` density -/

/-- (`cor:MCAlg-L2-dense`) The image of the matrix-coefficient
star-subalgebra in `L²(G)` (under the standard `C(G) ↪ L²(G)`
inclusion) is dense in `L²(G)`. -/
theorem matrixCoeffSubalgebra_dense_L2 :
    Dense (PeterWeyl.continuousMapToL2 G ''
      (matrixCoeffSubalgebra G : Set C(G, ℂ))) := by
  -- Uniform density of A in C(G, ℂ).
  have h_dense : Dense (matrixCoeffSubalgebra G : Set C(G, ℂ)) := by
    rw [dense_iff_closure_eq]
    have h_top := matrixCoeffSubalgebra_topologicalClosure_eq_top (G := G)
    have h_coe : ((matrixCoeffSubalgebra G).topologicalClosure : Set C(G, ℂ))
        = closure (matrixCoeffSubalgebra G : Set C(G, ℂ)) :=
      StarSubalgebra.topologicalClosure_coe _
    have h_univ : ((matrixCoeffSubalgebra G).topologicalClosure : Set C(G, ℂ))
        = Set.univ := by rw [h_top]; exact StarSubalgebra.coe_top
    rw [h_coe] at h_univ
    exact h_univ
  -- `continuousMapToL2 G` is continuous (it's a CLM) with dense range.
  have h_DR := PeterWeyl.continuousMapToL2_denseRange (G := G)
  exact h_DR.dense_image (PeterWeyl.continuousMapToL2 G).continuous h_dense

end UnitaryRep
